// Package claimcheck provides the Claim Check EIP pattern over
// messaging.Channel[T].
//
// Claim Check has two endpoints that work as a pair:
//
//   - ClaimCheckIn[T]   — heavy-payload producer side. Subscribes to a
//     source Channel[T] of the original heavy Message[T] envelopes,
//     stores each one in a MessageStore[T] under a generated key, and
//     forwards only a lightweight Message[ClaimCheckReference] to the
//     downstream Channel[ClaimCheckReference]. The downstream channel
//     and any intermediate channels carry only the reference — never
//     the payload — so per-hop memory, broker bandwidth, queue depth
//     and serialization cost are bounded by the size of the reference,
//     not the size of the payload.
//   - ClaimCheckOut[T]  — heavy-payload consumer side. Subscribes to a
//     source Channel[ClaimCheckReference], retrieves the original
//     Message[T] from the MessageStore[T] (using the reference's key),
//     and forwards the original envelope to a downstream Channel[T]
//     where actual processing happens. Optionally deletes the entry
//     after retrieval (default: yes — fire-and-forget claim, the store
//     does not grow).
//
// # Use cases
//
//   - Large blobs (PDFs, images, ML feature vectors, full HTTP request
//     bodies) that exceed a broker's per-message size limit (Kafka 1
//     MiB default, SQS 256 KiB, …).
//   - Pipelines where most stages only need the message identity for
//     routing and only one terminal stage needs the payload.
//   - Memory-constrained queues where keeping every in-flight envelope
//     materialized would exhaust the buffer.
//
// # Two endpoints, one store
//
// In and Out are independent components — each lives in its own
// lifecycle.Component. The link between them is the shared
// MessageStore[T]: ClaimCheckIn writes, ClaimCheckOut reads. The store
// is caller-owned; nothing in this package starts or stops it.
// Multiple In/Out pairs may share a store, or each pair may have its
// own — the consumer decides based on key-collision and lifetime
// concerns.
//
// # CorrelationID is preserved on the reference
//
// ClaimCheckIn copies the original message's Headers.CorrelationID to
// the reference message so downstream observers can correlate the
// reference hop to the original flow (and to the eventual
// ClaimCheckOut Get). The reference's MessageID is generated fresh
// (the reference is a NEW envelope; using the original MessageID
// would collide with the original on dedup paths).
//
// # Lifecycle
//
// Both endpoints implement common/lifecycle.Component (worker-style):
// Start registers the subscription on the source channel and returns
// immediately; Stop cancels the subscription and closes Done. Neither
// endpoint spawns goroutines of its own — dispatch concurrency is
// inherited from the source channel implementation.
//
// # Error handling
//
// The handler installed on the source channel always returns nil.
// Claim Check concerns (store Put/Get failure, forward Send failure)
// flow through the endpoint's WithErrorHandler hook (defaulting to
// messaging.DefaultErrorHandler which logs via common/log). Nothing
// propagates to the source channel's Send caller error path,
// consistent with the package-wide policy in
// modules/messaging/CODING_STANDARDS.md.
//
// Store failures are fail-CLOSED on both endpoints: a Put failure on
// In means the reference is NOT forwarded (the payload was never
// stored, downstream cannot recover); a Get failure on Out means the
// original is NOT forwarded (the payload is gone, forwarding a nil
// envelope would be worse). Delete failures on Out are reported but
// the original is still forwarded — losing the chance to clean up the
// store is preferable to losing the message.
package claimcheck

import (
	"github.com/guidomantilla/yarumo/core/common/lifecycle"
)

var (
	_ ClaimCheckIn[any]  = (*claimCheckIn[any])(nil)
	_ ClaimCheckOut[any] = (*claimCheckOut[any])(nil)

	_ ErrClaimCheckFn = ErrClaimCheck
	_ KeyGenFn        = defaultKeyGen
)

// ClaimCheckReference is the lightweight envelope-payload forwarded
// downstream by ClaimCheckIn in lieu of the heavy original Message[T].
// It carries only the key under which the original is stored in the
// MessageStore[T]; ClaimCheckOut uses that key to retrieve the
// original.
//
// The struct is intentionally minimal — only Key. If a future use
// case needs sidecar metadata (size hint, content-type override,
// per-claim TTL), add fields here behind a backwards-compatible
// migration.
type ClaimCheckReference struct {
	// Key is the opaque identifier under which the original
	// Message[T] was stored. It is generated by ClaimCheckIn (via the
	// configured KeyGenFn) and consumed by ClaimCheckOut.
	Key string
}

// ClaimCheckIn is the public interface for the heavy-payload producer
// side of Claim Check. It embeds lifecycle.Component so callers wire
// it up with lifecycle.Build. The interface exists (rather than
// returning lifecycle.Component directly) so the consumer's API
// surface preserves "this is a ClaimCheckIn" semantics and the type
// stays open to future endpoint-specific methods without breaking
// callers.
type ClaimCheckIn[T any] interface {
	lifecycle.Component
}

// ClaimCheckOut is the public interface for the heavy-payload consumer
// side of Claim Check. It embeds lifecycle.Component so callers wire
// it up with lifecycle.Build. The interface exists (rather than
// returning lifecycle.Component directly) so the consumer's API
// surface preserves "this is a ClaimCheckOut" semantics and the type
// stays open to future endpoint-specific methods without breaking
// callers.
type ClaimCheckOut[T any] interface {
	lifecycle.Component
}

// KeyGenFn returns a fresh opaque key used by ClaimCheckIn to address
// the offloaded message in the MessageStore[T]. Implementations must
// produce a value that is unique across the lifetime of the store
// they target — collisions cause silent overwrite by MessageStore.Put.
// The default (defaultKeyGen) draws from crypto/rand and emits a
// 128-bit hex string; replace via WithKeyGen when a different scheme
// is required (incremental counter for tests, ULID, broker-supplied
// id, …).
type KeyGenFn func() string

// ErrClaimCheckFn is the function type for ErrClaimCheck.
type ErrClaimCheckFn func(causes ...error) error
