# (mandatory)
# Path to coverprofile file (output of `go test -coverprofile` command).
profile: .reports/testcoverage.out

# (optional; but recommended to set)
local-prefix: "github.com/guidomantilla/yarumo/extensions/security/authn/grpc"

threshold:
  file: 85
  package: 90
  total: 90
