linters:
  enable:
    - gosec
    - staticcheck
    - forbidigo

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA9003"
      path: "_test.go$"

forbidigo:
  forbid:
    - "os.Getenv"
    - "os.LookupEnv"
    - "os.Setenv"
    - "os.Unsetenv"
    - "os.ExpandEnv"        # optional
    - "syscall.Getenv"      # optional