# (mandatory)
# Path to coverprofile file (output of `go test -coverprofile` command).
profile: .reports/testcoverage.out

# (optional; but recommended to set)
# When specified, reported file paths will not contain local prefix in the output
local-prefix: "github.com/guidomantilla/yarumo/managed"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0)
  # The minimum coverage that each file should have
  file: 83

  # (optional; default 0)
  # The minimum coverage that each package should have
  package: 83

  # (optional; default 0)
  # The minimum total coverage a project should have
  total: 95
