linters:
  enable:
    - gosec
    - staticcheck
    - forbidigo
    - depguard
    - gochecknoinits

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA9003"
      path: "_test.go$"
    - linters:
        - staticcheck
      text: "SA1012"
      path: "_test.go$"
    - linters:
        - gochecknoinits
        - gosec
      path: "_test.go$"

linters-settings:
  depguard:
    rules:
      main:
        deny:
          # ------------------------------------------------------------------------
          # LOGGING
          # ------------------------------------------------------------------------
          - pkg: "log"
            desc: "use zerolog instead of stdlib log"
          - pkg: "github.com/sirupsen/logrus"
            desc: "use zerolog instead of stdlib log"
          - pkg: "go.uber.org/zap"
            desc: "use zerolog instead of stdlib log"

          # ------------------------------------------------------------------------
          # INSECURE CRYPTO
          # ------------------------------------------------------------------------
          - pkg: "crypto/md5"
            desc: "crypto/md5 is insecure. use crypto/sha256"
          - pkg: "crypto/sha1"
            desc: "crypto/sha1 is insecure. use crypto/sha256"

          # ------------------------------------------------------------------------
          # INSECURE RAND
          # ------------------------------------------------------------------------
          - pkg: "^math/random$"
            desc: "use math/random/v2 or crypto/random instead"

          # ------------------------------------------------------------------------
          # DEPRECATED IO
          # ------------------------------------------------------------------------
          - pkg: "io/ioutil"
            desc: "ioutil is deprecated since Go 1.16"

          # ------------------------------------------------------------------------
          # LEGACY ERRORS
          # ------------------------------------------------------------------------
          - pkg: "github.com/pkg/errors"
            desc: "use standard package errors or fmt.Errorf with %w"

          # ------------------------------------------------------------------------
          # OLD LIBRARIES
          # ------------------------------------------------------------------------
          - pkg: "github.com/mitchellh/mapstructure"
            desc: "avoid untyped mapping; prefer typed structs + json"
          - pkg: "github.com/bitly/go-simplejson"
            desc: "avoid dynamic JSON; use encoding/json or gjson"

          # ------------------------------------------------------------------------
          # FORBIDDEN PACKAGES
          # -------------------------------------------------------------------------
          - pkg: "net/http/pprof"
            desc: "pprof should not be imported directly except in tools"
          - pkg: "runtime/pprof"
            desc: "prevent accidental CPU profiling in production code"
          - pkg: "runtime/debug"
            desc: "do not use ReadBuildInfo, SetGCPercent, etc. in prod"
          - pkg: unsafe
            desc: "unsafe must not be used outside low-level internal packages"

          # ------------------------------------------------------------------------
          # AVOID XML / GOB
          # ------------------------------------------------------------------------
          - pkg: encoding/xml
            desc: "avoid XML if possible; prefer JSON or protobuf"
          - pkg: encoding/gob
            desc: "gob is insecure and non-portable; avoid using it"

          # ------------------------------------------------------------------------
          # SYSTEM / DEBUG
          # ------------------------------------------------------------------------
          - pkg: syscall
            desc: "syscall is deprecated; use golang.org/x/sys"
          - pkg: debug/elf
            desc: "debug/elf should not be used outside tools"
          - pkg: debug/macho
            desc: "debug/macho should not be used outside tools"

  forbidigo:
    forbid:
      - p: ^print(ln)?$
      - p: os.Getenv
      - p: os.LookupEnv
      - p: os.Setenv
      - p: os.Unsetenv
      - p: os.ExpandEnv
      - p: syscall.Getenv
      - p: fmt.Println
      - p: fmt.Fprintln
      - p: fmt.Printf
      - p: fmt.Fprintf
      - p: fmt.Print
      - p: fmt.Fprint